// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: mail.proto

package mail_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailServiceClient interface {
	SendOnboardingEmail(ctx context.Context, in *AccountOnboardingEmail, opts ...grpc.CallOption) (*AccountOnboardingEmailResponse, error)
	SendAccountRegistrationEmailAction(ctx context.Context, in *AccountRegistrationActionEmail, opts ...grpc.CallOption) (*AccountRegistrationActionResponse, error)
	SendAccountEmailVerification(ctx context.Context, in *AccountEmailVerification, opts ...grpc.CallOption) (*AccountEmailVerificationResponse, error)
	SendVerificationMessage(ctx context.Context, in *SendKorlabVerificationEmail, opts ...grpc.CallOption) (*SendKorlabVerificationResponse, error)
	SendAdminRegistrationEmail(ctx context.Context, in *SendAdminRegistrationEmailRequest, opts ...grpc.CallOption) (*SendAdminRegistrationEmailResponse, error)
}

type mailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailServiceClient(cc grpc.ClientConnInterface) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) SendOnboardingEmail(ctx context.Context, in *AccountOnboardingEmail, opts ...grpc.CallOption) (*AccountOnboardingEmailResponse, error) {
	out := new(AccountOnboardingEmailResponse)
	err := c.cc.Invoke(ctx, "/otp.MailService/SendOnboardingEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendAccountRegistrationEmailAction(ctx context.Context, in *AccountRegistrationActionEmail, opts ...grpc.CallOption) (*AccountRegistrationActionResponse, error) {
	out := new(AccountRegistrationActionResponse)
	err := c.cc.Invoke(ctx, "/otp.MailService/SendAccountRegistrationEmailAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendAccountEmailVerification(ctx context.Context, in *AccountEmailVerification, opts ...grpc.CallOption) (*AccountEmailVerificationResponse, error) {
	out := new(AccountEmailVerificationResponse)
	err := c.cc.Invoke(ctx, "/otp.MailService/SendAccountEmailVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendVerificationMessage(ctx context.Context, in *SendKorlabVerificationEmail, opts ...grpc.CallOption) (*SendKorlabVerificationResponse, error) {
	out := new(SendKorlabVerificationResponse)
	err := c.cc.Invoke(ctx, "/otp.MailService/SendVerificationMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendAdminRegistrationEmail(ctx context.Context, in *SendAdminRegistrationEmailRequest, opts ...grpc.CallOption) (*SendAdminRegistrationEmailResponse, error) {
	out := new(SendAdminRegistrationEmailResponse)
	err := c.cc.Invoke(ctx, "/otp.MailService/SendAdminRegistrationEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
// All implementations must embed UnimplementedMailServiceServer
// for forward compatibility
type MailServiceServer interface {
	SendOnboardingEmail(context.Context, *AccountOnboardingEmail) (*AccountOnboardingEmailResponse, error)
	SendAccountRegistrationEmailAction(context.Context, *AccountRegistrationActionEmail) (*AccountRegistrationActionResponse, error)
	SendAccountEmailVerification(context.Context, *AccountEmailVerification) (*AccountEmailVerificationResponse, error)
	SendVerificationMessage(context.Context, *SendKorlabVerificationEmail) (*SendKorlabVerificationResponse, error)
	SendAdminRegistrationEmail(context.Context, *SendAdminRegistrationEmailRequest) (*SendAdminRegistrationEmailResponse, error)
	mustEmbedUnimplementedMailServiceServer()
}

// UnimplementedMailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMailServiceServer struct {
}

func (UnimplementedMailServiceServer) SendOnboardingEmail(context.Context, *AccountOnboardingEmail) (*AccountOnboardingEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOnboardingEmail not implemented")
}
func (UnimplementedMailServiceServer) SendAccountRegistrationEmailAction(context.Context, *AccountRegistrationActionEmail) (*AccountRegistrationActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAccountRegistrationEmailAction not implemented")
}
func (UnimplementedMailServiceServer) SendAccountEmailVerification(context.Context, *AccountEmailVerification) (*AccountEmailVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAccountEmailVerification not implemented")
}
func (UnimplementedMailServiceServer) SendVerificationMessage(context.Context, *SendKorlabVerificationEmail) (*SendKorlabVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVerificationMessage not implemented")
}
func (UnimplementedMailServiceServer) SendAdminRegistrationEmail(context.Context, *SendAdminRegistrationEmailRequest) (*SendAdminRegistrationEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAdminRegistrationEmail not implemented")
}
func (UnimplementedMailServiceServer) mustEmbedUnimplementedMailServiceServer() {}

// UnsafeMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailServiceServer will
// result in compilation errors.
type UnsafeMailServiceServer interface {
	mustEmbedUnimplementedMailServiceServer()
}

func RegisterMailServiceServer(s grpc.ServiceRegistrar, srv MailServiceServer) {
	s.RegisterService(&MailService_ServiceDesc, srv)
}

func _MailService_SendOnboardingEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountOnboardingEmail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendOnboardingEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.MailService/SendOnboardingEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendOnboardingEmail(ctx, req.(*AccountOnboardingEmail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendAccountRegistrationEmailAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRegistrationActionEmail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendAccountRegistrationEmailAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.MailService/SendAccountRegistrationEmailAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendAccountRegistrationEmailAction(ctx, req.(*AccountRegistrationActionEmail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendAccountEmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountEmailVerification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendAccountEmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.MailService/SendAccountEmailVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendAccountEmailVerification(ctx, req.(*AccountEmailVerification))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendVerificationMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendKorlabVerificationEmail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendVerificationMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.MailService/SendVerificationMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendVerificationMessage(ctx, req.(*SendKorlabVerificationEmail))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendAdminRegistrationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAdminRegistrationEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendAdminRegistrationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.MailService/SendAdminRegistrationEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendAdminRegistrationEmail(ctx, req.(*SendAdminRegistrationEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailService_ServiceDesc is the grpc.ServiceDesc for MailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otp.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOnboardingEmail",
			Handler:    _MailService_SendOnboardingEmail_Handler,
		},
		{
			MethodName: "SendAccountRegistrationEmailAction",
			Handler:    _MailService_SendAccountRegistrationEmailAction_Handler,
		},
		{
			MethodName: "SendAccountEmailVerification",
			Handler:    _MailService_SendAccountEmailVerification_Handler,
		},
		{
			MethodName: "SendVerificationMessage",
			Handler:    _MailService_SendVerificationMessage_Handler,
		},
		{
			MethodName: "SendAdminRegistrationEmail",
			Handler:    _MailService_SendAdminRegistrationEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
